$(document).ready(function(){
    $(".design").click(function(){
        $(".designp").toggle();
    });
    $(".development").click(function(){
        $(".developmentp").toggle();
    });
    $(".product").click(function(){
        $(".productp").toggle();
    });
});